### ISSUE TITLE
Make StaticPage Action and View

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#15]
静的なページの実装
基本的にアクションは実装しない（はず）。

index
    トップページ、様々なページヘのリンクを貼る。
    [旧ゼミページ](http://www.lanet.sist.chukyo-u.ac.jp/index.php/Introduction)を参考に必要項目を埋める。

activities
    活動記録を表示するページ、旧ページでは[News](http://www.lanet.sist.chukyo-u.ac.jp/index.php/News)に値する。
　実装する場合、別で分ける可能性あり（ちょっと悩んでます、必要かどうか意見ください）。

equipment
    めんどくさくてこっちに持ってきてしまった備品管理ページ
    最近結構PC類とか買ってるし、これもモデルとコントローラを別で分けたほうがいいかも。意見ください。

publications
    [学会活動](http://www.lanet.sist.chukyo-u.ac.jp/index.php/Publications)
    学会なんて久しく行ってないみたいだしこっちでええやろ。
    ただし過去の学会活動がそこそこあるので入力がめんどくさい模様。

jobs
    [就職先一覧](http://www.lanet.sist.chukyo-u.ac.jp/index.php/Job_Hunting)
    リンク先を参考に、すんごいゲーム会社とヤフーは外せない。

links
    [外部リンク](http://www.lanet.sist.chukyo-u.ac.jp/index.php/Links)
    リンク先を参考に。
    面白ソフト・最新技術紹介は新しいのに変えたほうがよいかも。

**Comment by kichinaga** [comment]
equipmentは別で作ることとなったので
rails destroy controller StaticPages equipment
で削除する

**Comment by hato52** [comment]
そのコマンド使うとequipmentのアクションとかviewだけに限らずStaticPagesのcontrollerto
view全部消えちゃいますけど、消してからまたStaticPagesを作り直せば大丈夫ですか？

**Comment by kichinaga** [comment]
ごめん気づくの遅れた

コマンド間違ってた  
rails destroy controller StaticPages equipments  
です

**Comment by hato52** [comment]
そのコマンドでも結果変わりませんでした...

**Comment by kichinaga** [comment]
できたと思ったんだがなあ...

コマンドは使わず
static_pages_controller.rb 内のequipmentの記述を削除
app/views/static_pages/equipment.html.erb を削除
config/routes.rb 内のequipmentに関するルーティングの記述を削除

で対応しよう

**Comment by hato52** [comment]
0bfa6579dda22b475230141c6c5005512bfacb02
のコミットで削除しておきました

**Comment by hato52** [comment]
1290d0480d5d4b46450acc57b1f7443fce136508 81e53e535577926cdd13a2088c143dd914f7641e
のコミットでpublications、jobsの中身を書いておきました。
デザインの修正とかコンテンツの書き足しとかあったらよろしくお願いします。
