### ISSUE TITLE
Fix login form

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#16]
フォームのフィールドをemail_fieldからtext_fieldへ修正する。

https://github.com/LashkiaSemi/HomePage/blob/548063d3e228831787e8a2f53e9ef0a8e1394e98/app/views/sessions/login_form.html.erb#L8

**Comment by hato52** [comment]
b4715f1ff8b48b3322f688ef787704d6407b6895 で修正しました。
