### ISSUE TITLE
create equipment page

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#17]
備品管理ページの作成

model: Equipment
* name: string (備品名)
* num: integer (数)
* note: string (備考、何かしら追記したいことを記述)

model: Tag
* equipment: references
* name: string

TagとEquipmentは１対１で関連付けてください。  

<br>

　* が前につくアクションは、Admin以上の権限でなければroot_urlへリダイレクトするように
（上の動作を行う関数をUserHelper上に定義してbefore_actionで指定してやったほうが多分楽）

controller: EquipmentsController
* index
equipmentをタグ分けでして一覧表示。
ログインユーザーがAdmin以上の権限を持っていれば、上に新規作成ボタン１つ設置し、編集、削除ボタンを各備品一覧の横につける。
* 　* new , create
新規作成画面、各フォームを作成。
* 　* edit , update
更新画面、上とほぼ同じ実装になるはず。
* 　* destroy
Viewは作らずダイアログで削除するか確認。

<br>

controller: TagsController
* 　* index
 一覧表示と削除ボタンのみ設定
* 　* new, create
普通の新規作成画面
* 　* destroy 
上と同じ削除ダイアログの実装

Tagのコントローラーは編集ページを作らず、新規作成と削除機構だけにします。
変更したいときは削除してから新しく作りなおす形にします。

Viewのデザイン（BootStrap）は厳しそうならやらなくてもいいです。
聞きたいことがあればここ（issue）かSlackに送ってくれれば答えます。

**Comment by hato52** [comment]
ea1db7e63597f1cf2696aa956807c917b0006f3c
のコミットでとりあえずmodelとcontrollerを作成
viewはこれから作ります

**Comment by hato52** [comment]
プルするの忘れてて下のコミットまで出来ちゃってます
すいません...
639deeb592ae21197c397bcfca09f53d1275565e

**Comment by kichinaga** [comment]
プルリクじゃなく各々でdevelopにマージしてpushしてるから仕方ない。
コンフリクトの解消めんどいけど頑張りましょ

**Comment by hato52** [comment]
コンフリクト解消のためにこっちのローカルでやることあれば教えてもらえると嬉しいです…

**Comment by kichinaga** [comment]
多分地道に変更箇所を修正してくしかないわ
もしくはマージツール見たいのを使うくらいかな

もし厳しそうならプルリクで送ってくれればこっちでやっとくわ

**Comment by hato52** [comment]
今の状態でローカルのdevelopに進めた作業ブランチをマージして特にコンフリクト発生しなかったんですけど、なにか修正必要だったりします...？

最悪備品関連のコミット取り消してやり直した方がいいですかね？

**Comment by kichinaga** [comment]
https://github.com/LashkiaSemi/HomePage/blob/develop/db/schema.rb#L13

このあたりを自力で修正する（<<<<< と >>>>> で囲まれた部分）必要があるかな。

まあ今回のはschemaファイルだから多分rails db:migrate:resetで自動で修正できると思う。

**Comment by hato52** [comment]
遅くなっちゃいましたけどローカルのdevelopのschemaファイル修正しました。
これプッシュすれば大丈夫ですか？

**Comment by kichinaga** [comment]
多分大丈夫だと思います

**Comment by hato52** [comment]
6f236fde262d8432d0bae6b1d0de36c957ac5be3
で修正したやつコミットしました。
