### ISSUE TITLE
本番環境でログアウトできない

### ISSUE THREAD

**Issue by hato52** [LashkiaSemi/HomePage#21]
テスト環境では問題無さそうですが、本番環境でログアウト先が存在しないと言われます。

**Comment by kichinaga** [comment]
リクエストのメソッドがGETになってることが問題っぽい
DELETEメソッドでアクセスするように設定する必要がある

確かlink_to辺りでそれ関係の問題があったはず
調べてみてください

**Comment by hato52** [comment]
DELETEメソッドの処理はrails-ujsで行われているみたいです

開発環境ではrails-ujsを含めたjsファイルが読み込まれてますが、本番環境では読み込まれて無さそうなのでそのあたりが原因だと思います。

**Comment by kichinaga** [comment]
動きました

原因はアセットプリコンパイルをせずにサーバを起動していたためでした
次からは、js, css辺りの更新があれば
bundle exec rails assets:precompile
を行うようにしてください。
