### ISSUE TITLE
トップページにお知らせ表示の追加

### ISSUE THREAD

**Issue by hato52** [LashkiaSemi/HomePage#23]
トップページにお知らせの欄を追加してほしいとのことです

余裕があれば動的に内容を追加できるようにしたほうが便利かも

**Comment by hato52** [comment]
eeb7a570543208dc87dc8602d576eb9fe2e53f93
のコミットでとりあえず追加

**Comment by kichinaga** [comment]
流石にモデル作った方が良いだろうなあ
お知らせ更新するたびにコード変えてgithubにアップしてそれをpullするなんてクソ面倒くさいし
