### ISSUE TITLE
前のゼミページが検索履歴に引っかかってる問題

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#24]
前のゼミのページが検索履歴に引っかかってる

ipアドレスモロバレだしちょっとヤバイかもしれん

ちょっと原因調査した方が良さげ

**Comment by kichinaga** [comment]
前のサーバは止めた？

**Comment by hato52** [comment]
前のWEBサーバも起動しちゃってますね…
止めておきます

**Comment by hato52** [comment]
とりあえず前のWEBサーバは停止させときました
