### ISSUE TITLE
flashの存在を消す

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#25]
寂しいかなと思って前ホームページのflash持ってきたけど
「This is supposed to be a flash animation. You'll need the flash plugin and a browser that supports it to view it.」
って表示される。

やっぱりflashに人権なんてなかったんや...

**Comment by hato52** [comment]
448e1f48a71e0e14c25796a663e4a5f104dc256a
のコミットでflashに引退してもらいました。

とりあえずフリー素材使って簡単なトップ画像を置いただけなんで、もっとイケてる感じのに変更してもらえると助かります。

**Comment by kichinaga** [comment]
💯
