### ISSUE TITLE
Add model Validation

### ISSUE THREAD

**Issue by kichinaga** [LashkiaSemi/HomePage#7]
各モデルにバリデーションを設定してください。

とりあえず存在性の設定と
文字数変わらないであろう学籍番号に文字数のバリデーションをかけときましょ

**Comment by kichinaga** [comment]
パスワードを自動で暗号化してくれるbcryptを利用できるように
Userモデルの中にhas_secure_passwordと追記

**Comment by hato52** [comment]
バリデーションの追加をしました。
ついでにdocumentsモデルの要素に名前の誤りがあったんで修正しておきました。

**Comment by hato52** [comment]
c28b3605d0a5e40cabd512e1b0a30d57ff6c8e4f 
のコミットでバリデーションの設定をしました。
